name: k_skin_example
description: A demonstration app for the k_skin package.
version: 1.0.0+1

environment:
  sdk: ^3.8.0-92.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  k_skin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
